use super::params::{camel_to_kebab, parse_params};
use rmcp::model::Tool;

/// Return the current time as a Unix timestamp (seconds since epoch).
fn unix_now() -> u64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

/// Generate a bash script wrapper for a single MCP tool.
///
/// The script:
/// - Parses named `--flag value` CLI arguments derived from `inputSchema`.
/// - Validates required parameters before calling the server.
/// - Builds a JSON payload via `jq`.
/// - Calls `cast-mcp-client call <server> <tool> <json>`.
/// - Parses MCP output: text to stdout, `isError` to stderr (exit 1),
///   non-text warned.
pub fn generate_script(server_name: &str, tool: &Tool) -> String {
    let tool_name = tool.name.as_ref();
    let description = tool.description.as_deref().unwrap_or("").trim().to_string();
    let script_name = format!("{}-{}", server_name, camel_to_kebab(tool_name));
    let params = parse_params(tool);

    let mut s = String::new();

    // ── Header ──────────────────────────────────────────────────────────────
    s.push_str("#!/usr/bin/env bash\n");
    // Write the description as a commented block so that multi-line
    // descriptions (common in real MCP servers) don't leak unquoted prose
    // into the script.
    s.push_str(&format!("# {}:", script_name));
    for line in description.lines() {
        s.push_str(&format!("\n# {}", line));
    }
    s.push('\n');
    s.push_str("# Generated by cast-mcp-client generate\n");
    s.push_str(&format!(
        "# Server: {} | Tool: {}\n\n",
        server_name, tool_name
    ));
    s.push_str("set -euo pipefail\n\n");
    s.push_str(&format!("SERVER=\"{}\"\n", server_name));
    s.push_str(&format!("TOOL=\"{}\"\n\n", tool_name));

    // ── Usage function ───────────────────────────────────────────────────────
    s.push_str("usage() { cat <<'EOF'\n");
    s.push_str(&format!("Usage: {} [OPTIONS]\n", script_name));
    if !description.is_empty() {
        s.push_str(&format!("{}\n", description));
    }
    s.push('\n');
    s.push_str("Options:\n");
    for p in &params {
        let req_label = if p.required {
            "(required)"
        } else {
            "(optional)"
        };
        s.push_str(&format!(
            "  --{} {}    {} {}\n",
            p.flag, p.type_hint, req_label, p.description
        ));
    }
    s.push_str("  -h, --help          Show this help\n");
    s.push_str("EOF\n}\n\n");

    // ── Variable declarations ────────────────────────────────────────────────
    for p in &params {
        s.push_str(&format!("{}=\"\"\n", p.var));
    }
    s.push('\n');

    // ── Argument parsing loop ────────────────────────────────────────────────
    s.push_str("while [[ $# -gt 0 ]]; do\n");
    s.push_str("  case \"$1\" in\n");
    for p in &params {
        s.push_str(&format!(
            "    --{flag}) [[ $# -lt 2 ]] && {{ echo \"Error: --{flag} requires a value\" >&2; exit 1; }}; {var}=\"$2\"; shift 2 ;;\n",
            flag = p.flag,
            var = p.var,
        ));
    }
    s.push_str("    -h|--help) usage; exit 0 ;;\n");
    s.push_str("    *) echo \"Unknown option: $1\" >&2; usage >&2; exit 1 ;;\n");
    s.push_str("  esac\n");
    s.push_str("done\n\n");

    // ── Required param validation ────────────────────────────────────────────
    for p in params.iter().filter(|p| p.required) {
        s.push_str(&format!(
            "[[ -z \"${{{}:-}}\" ]] && {{ echo \"Error: --{} is required\" >&2; exit 1; }}\n",
            p.var, p.flag
        ));
    }
    if params.iter().any(|p| p.required) {
        s.push('\n');
    }

    // ── JSON payload construction ────────────────────────────────────────────
    // Accumulate --arg/--argjson flags into a bash array, then call
    // jq -n '$ARGS.named' exactly once — O(1) subprocess spawns regardless
    // of parameter count.
    s.push_str("JQ_ARGS=()\n");
    for p in &params {
        let jq_flag = if p.json_arg { "--argjson" } else { "--arg" };
        if p.required {
            // Always included — validation already guarantees non-empty.
            s.push_str(&format!(
                "JQ_ARGS+=({} {} \"${{{}}}\")\n",
                jq_flag, p.name, p.var
            ));
        } else {
            // Conditionally included only when the user provided a value.
            s.push_str(&format!(
                "[[ -n \"${{{}:-}}\" ]] && JQ_ARGS+=({} {} \"${{{}}}\")\n",
                p.var, jq_flag, p.name, p.var
            ));
        }
    }
    s.push_str("PARAMS=$(jq -n \"${JQ_ARGS[@]}\" '$ARGS.named')\n");
    s.push('\n');

    // ── Call cast-mcp-client ─────────────────────────────────────────────────
    s.push_str("RESULT=$(cast-mcp-client call \"$SERVER\" \"$TOOL\" \"$PARAMS\"); STATUS=$?\n");
    s.push_str("[[ $STATUS -ne 0 ]] && { echo \"$RESULT\" >&2; exit $STATUS; }\n\n");

    // ── MCP output parsing ───────────────────────────────────────────────────
    s.push_str("IS_ERROR=$(echo \"$RESULT\" | jq -r '.isError // false')\n");
    s.push_str("[[ \"$IS_ERROR\" == \"true\" ]] && {\n");
    s.push_str("  echo \"$RESULT\" | jq -r '.content[]?|select(.type==\"text\")|.text' >&2\n");
    s.push_str("  exit 1\n");
    s.push_str("}\n\n");
    s.push_str("NON_TEXT=$(echo \"$RESULT\" | jq -r '[.content[]?|select(.type!=\"text\")|.type]|unique|join(\", \")')\n");
    s.push_str(
        "[[ -n \"$NON_TEXT\" ]] && echo \"Warning: ignored non-text type(s): $NON_TEXT\" >&2\n\n",
    );
    s.push_str("echo \"$RESULT\" | jq -r '[.content[]?|select(.type==\"text\")|.text]|join(\"\")'");

    s
}

/// Return the current Unix timestamp — used when writing `manifest.json`.
pub(crate) fn now_unix() -> u64 {
    unix_now()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_script_missing_flag_value_guard() {
        // Each --flag case must guard against a missing value before accessing
        // $2. Without the guard, `set -u` fires with the unhelpful "unbound
        // variable" error when the user passes --flag as the last argument.
        let schema = serde_json::json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Search query" }
            },
            "required": ["query"]
        });
        let tool = rmcp::model::Tool::new_with_raw(
            "search".to_string(),
            Some("Search something".into()),
            schema.as_object().cloned().unwrap_or_default(),
        );
        let script = generate_script("cast", &tool);

        // The guard must appear in the argument-parsing case arm for --query.
        assert!(
            script.contains("--query) [[ $# -lt 2 ]]"),
            "missing guard: {script}"
        );
        // The error message must name the offending flag.
        assert!(
            script.contains("--query requires a value"),
            "missing error message: {script}"
        );
    }

    #[test]
    fn test_generate_script_content() {
        let schema = serde_json::json!({
            "type": "object",
            "properties": {
                "message": { "type": "string",  "description": "The message to send" },
                "count":   { "type": "integer", "description": "Number of repeats" }
            },
            "required": ["message"]
        });
        let tool = rmcp::model::Tool::new_with_raw(
            "dummy_tool".to_string(),
            Some("A mock tool".into()),
            schema.as_object().cloned().unwrap_or_default(),
        );
        let script = generate_script("cast", &tool);

        // Shebang + header
        assert!(script.starts_with("#!/usr/bin/env bash"), "missing shebang");
        assert!(script.contains("cast-dummy-tool"), "script name in header");
        assert!(script.contains("A mock tool"), "description in header");

        // Flags in usage
        assert!(script.contains("--message"), "required flag --message");
        assert!(script.contains("--count"), "optional flag --count");
        assert!(script.contains("(required)"), "required marker");
        assert!(script.contains("(optional)"), "optional marker");
        assert!(script.contains("STRING"), "string type hint");
        assert!(script.contains("INTEGER"), "integer type hint");

        // Validation for required param
        assert!(
            script.contains("--message is required"),
            "required validation message"
        );

        // jq type handling: string uses --arg, integer uses --argjson
        assert!(script.contains("--arg message"), "string param uses --arg");
        assert!(
            script.contains("--argjson count"),
            "integer param uses --argjson"
        );

        // Single jq invocation via JQ_ARGS array
        assert!(script.contains("JQ_ARGS=()"), "JQ_ARGS array init");
        assert!(script.contains("jq -n"), "single jq -n invocation");
        assert!(script.contains("'$ARGS.named'"), "uses $ARGS.named builtin");
        assert!(
            !script.contains("echo \"$PARAMS\" | jq"),
            "no sequential pipe-to-jq pattern"
        );

        // SERVER/TOOL constants
        assert!(script.contains("SERVER=\"cast\""), "SERVER constant");
        assert!(script.contains("TOOL=\"dummy_tool\""), "TOOL constant");

        // Output parsing section
        assert!(script.contains("isError"), "isError check");
        assert!(
            script.contains("cast-mcp-client call"),
            "delegates to cast-mcp-client call"
        );

        // Null-safe content iteration: .content[]? not .content[]
        assert!(
            script.contains(".content[]?"),
            "uses .content[]? for null safety"
        );
        assert!(
            !script.contains(".content[]|"),
            "no bare .content[]| that crashes on null"
        );
    }

    #[test]
    fn test_generate_script_multiline_description() {
        // Descriptions from real MCP servers (e.g. Context7) are multi-line
        // prose. Every line that falls outside the heredoc must be prefixed
        // with '#' so bash does not attempt to execute prose as commands.
        let multiline_desc =
            "First line summary.\n\nYou MUST call this first.\n\nDo not call more than 3 times.";
        let schema = serde_json::json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "The query" }
            },
            "required": ["query"]
        });
        let tool = rmcp::model::Tool::new_with_raw(
            "search".to_string(),
            Some(multiline_desc.into()),
            schema.as_object().cloned().unwrap_or_default(),
        );
        let script = generate_script("myserver", &tool);

        // Every non-blank line before 'set -euo pipefail' must start with '#'.
        // (Heredoc content and the set line itself are exempt — we only check
        // the header block which is where the description is embedded.)
        let header: String = script
            .lines()
            .take_while(|l| !l.starts_with("set -euo pipefail"))
            .collect::<Vec<_>>()
            .join("\n");
        for line in header.lines() {
            if line.is_empty() {
                continue;
            }
            assert!(
                line.starts_with('#'),
                "Header line is not a comment: {:?}",
                line
            );
        }

        // The description text is present somewhere in the script.
        assert!(
            script.contains("First line summary."),
            "description in script"
        );
        assert!(
            script.contains("You MUST call this first."),
            "second paragraph present"
        );
    }
}
